Mostly taken from https://github.com/eric496/numpy-tutorial/blob/master/Complete%20Tutorial.ipynb

In [1]:
!pip install numpy

    100% |████████████████████████████████| 15.3MB 1.0MB/s eta 0:00:01    79% |█████████████████████████▎      | 12.1MB 8.1MB/s eta 0:00:01    94% |██████████████████████████████▏ | 14.4MB 7.2MB/s eta 0:00:01
You are using pip version 19.0.3, however version 20.2b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [47]:
import numpy as np

In [48]:
type(np)

module

In [49]:
np.log(10)

2.302585092994046

In [50]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [51]:
arr.dtype

dtype('int64')

In [52]:
arr[0]

1

In [53]:
len(arr)

5

In [54]:
arr.shape

(5,)

In [55]:
arr = np.array([1,2,3,4,5], dtype="float")
arr

array([1., 2., 3., 4., 5.])

In [56]:
arr.dtype

dtype('float64')

In [57]:
arr = np.array([1,2,3,4,5], dtype="int8")
arr

array([1, 2, 3, 4, 5], dtype=int8)

In [58]:
# Conversion
arr.astype("float")

array([1., 2., 3., 4., 5.])

In [59]:
# Overflow
arr = np.array([10000,2,3,4,5], dtype="int8")
arr

array([16,  2,  3,  4,  5], dtype=int8)

In [60]:
# Matrices
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
arr.shape

(2, 3)

In [62]:
# n rows
arr.shape[0]

2

In [63]:
# n columns
arr.shape[1]

3

In [64]:
arr.reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [65]:
arr.reshape((3, 2)).shape

(3, 2)

In [66]:
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [67]:
# np.linspace(from, to, how_many)
arr = np.linspace(2, 8, 4)
arr

array([2., 4., 6., 8.])

In [68]:
arr = np.random.rand(3, 2)
arr

array([[0.7146019 , 0.55452296],
       [0.79829162, 0.3823355 ],
       [0.79793593, 0.81311779]])

In [69]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [70]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [71]:
zeros = np.zeros_like(arr)
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [72]:
ones = np.ones_like(arr)
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [73]:
empty = np.empty((5,5))
empty

array([[3.10503618e+231, 3.10503618e+231, 7.90505033e-323,
        0.00000000e+000, 2.18565566e-312],
       [5.02034658e+175, 7.92417025e+165, 1.72403783e-047,
        5.05924436e-038, 6.15533356e+170],
       [9.95512671e-043, 3.59751658e+252, 8.93185432e+271,
        7.33723594e+223, 1.47763641e+248],
       [1.16096346e-028, 4.31443960e-096, 9.08366793e+223,
        7.92417025e+165, 1.72403783e-047],
       [5.05924436e-038, 6.15533356e+170, 2.24729348e+174,
        1.56605686e-076, 8.15064562e-043]])

In [74]:
full = np.full((4,4), 5)
full

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [75]:
# No axis specified, then flatten the input array first and repeat
arr = [[0, 1, 2], [3, 4, 5]]
np.repeat(arr, 3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [76]:
# An example of repeating along x-axis
arr = [[0, 1, 2], [3, 4, 5]]
np.repeat(arr, 3, axis=0)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [77]:
# An example of repeating along y-axis
arr = [[0, 1, 2], [3, 4, 5]]
np.repeat(arr, 3, axis=1)

array([[0, 0, 0, 1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4, 5, 5, 5]])

In [78]:
# Repeat the whole array by a specified number of times
arr = [0, 1, 2]
np.tile(arr, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [79]:
# Repeat along specified axes
np.tile(arr, (2,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [80]:
identity_matrix = np.eye(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [81]:
# Create a matrix given values on the diagonal
# All non-diagonal values set to zeros
arr = np.diag([1,2,3,4,5])
arr

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [82]:
print(np.info(arr))

class:  ndarray
shape:  (5, 5)
strides:  (40, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x7fe20c7924b0
byteorder:  little
byteswap:  False
type: int64
None


In [83]:
# Number of axis/dimensions
print(arr.ndim)

2


In [84]:
# Number of elements in the array
print(arr.size)

25


In [85]:
# Number of bytes per element
print(arr.itemsize)

8


In [86]:
# Total memory footprint
# arr.nbytes = arr.size * arr.itemsize
print(arr.nbytes)

200


In [87]:
np.random.seed(42)

In [88]:
# generate a random scalar in [0, 1) - uniform distribution
np.random.rand()

0.3745401188473625

In [89]:
# generate a random array of size 3 - uniform distribution
np.random.rand(3)

array([0.95071431, 0.73199394, 0.59865848])

In [90]:
# generate a 2-D array - uniform distribution
np.random.rand(3,3)

array([[0.15601864, 0.15599452, 0.05808361],
       [0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264]])

In [91]:
# generate random 2-D array - normal distribution, mean = 0, std = 1
np.random.randn(3,3)

array([[-0.58087813, -0.52516981, -0.57138017],
       [-0.92408284, -2.61254901,  0.95036968],
       [ 0.81644508, -1.523876  , -0.42804606]])

In [92]:
# generate ints in some interval np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 3))

[3 7 4]


In [93]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.59241457 0.04645041 0.60754485 0.17052412 0.06505159 0.94888554
 0.96563203 0.80839735 0.30461377 0.09767211]
[0.68423303 0.44015249 0.12203823 0.49517691 0.03438852 0.9093204
 0.25877998 0.66252228 0.31171108 0.52006802]
[0.54671028 0.18485446 0.96958463 0.77513282 0.93949894 0.89482735
 0.59789998 0.92187424 0.0884925  0.19598286]
[0.04522729 0.32533033 0.38867729 0.27134903 0.82873751 0.35675333
 0.28093451 0.54269608 0.14092422 0.80219698]


In [94]:
# generate random sample with given probabilities
print(np.random.choice(range(3), 10, replace=True, p=[0.1, 0.8, 0.1]))

[0 2 1 1 0 1 1 1 1 0]


In [95]:
arr = np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
# inplace
np.random.shuffle(arr)
arr

array([2, 4, 5, 1, 7, 0, 9, 3, 8, 6])

In [97]:
arr = np.random.randint(0, 10, (5, 5))
arr

array([[6, 6, 7, 4, 2],
       [7, 5, 2, 0, 2],
       [4, 2, 0, 4, 9],
       [6, 6, 8, 9, 9],
       [2, 6, 0, 3, 3]])

In [98]:
print(arr + 10)

[[16 16 17 14 12]
 [17 15 12 10 12]
 [14 12 10 14 19]
 [16 16 18 19 19]
 [12 16 10 13 13]]


In [99]:
print(arr - 10)

[[ -4  -4  -3  -6  -8]
 [ -3  -5  -8 -10  -8]
 [ -6  -8 -10  -6  -1]
 [ -4  -4  -2  -1  -1]
 [ -8  -4 -10  -7  -7]]


In [100]:
print(arr * 10)

[[60 60 70 40 20]
 [70 50 20  0 20]
 [40 20  0 40 90]
 [60 60 80 90 90]
 [20 60  0 30 30]]


In [101]:
print(arr / 10)

[[0.6 0.6 0.7 0.4 0.2]
 [0.7 0.5 0.2 0.  0.2]
 [0.4 0.2 0.  0.4 0.9]
 [0.6 0.6 0.8 0.9 0.9]
 [0.2 0.6 0.  0.3 0.3]]


In [102]:
arr1 = np.array([1,2,3])
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memoryarr = np.array([1,2,3])
np.add(arr1, [8,9,10], out=arr1)
print(arr1)

[ 9 11 13]


In [103]:
np.subtract(arr1, [8,9,10], out=arr1)
print(arr1)

[1 2 3]


In [104]:
np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[1 4 9]


In [105]:
print(np.exp(arr))

[[4.03428793e+02 4.03428793e+02 1.09663316e+03 5.45981500e+01
  7.38905610e+00]
 [1.09663316e+03 1.48413159e+02 7.38905610e+00 1.00000000e+00
  7.38905610e+00]
 [5.45981500e+01 7.38905610e+00 1.00000000e+00 5.45981500e+01
  8.10308393e+03]
 [4.03428793e+02 4.03428793e+02 2.98095799e+03 8.10308393e+03
  8.10308393e+03]
 [7.38905610e+00 4.03428793e+02 1.00000000e+00 2.00855369e+01
  2.00855369e+01]]


In [106]:
print(np.log(arr))

[[1.79175947 1.79175947 1.94591015 1.38629436 0.69314718]
 [1.94591015 1.60943791 0.69314718       -inf 0.69314718]
 [1.38629436 0.69314718       -inf 1.38629436 2.19722458]
 [1.79175947 1.79175947 2.07944154 2.19722458 2.19722458]
 [0.69314718 1.79175947       -inf 1.09861229 1.09861229]]


/Users/roman/.pyenv/versions/3.7.3/envs/iasa_kpi_ml_course/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


In [107]:
print(np.cos(arr))

[[ 0.96017029  0.96017029  0.75390225 -0.65364362 -0.41614684]
 [ 0.75390225  0.28366219 -0.41614684  1.         -0.41614684]
 [-0.65364362 -0.41614684  1.         -0.65364362 -0.91113026]
 [ 0.96017029  0.96017029 -0.14550003 -0.91113026 -0.91113026]
 [-0.41614684  0.96017029  1.         -0.9899925  -0.9899925 ]]


In [108]:
arr

array([[6, 6, 7, 4, 2],
       [7, 5, 2, 0, 2],
       [4, 2, 0, 4, 9],
       [6, 6, 8, 9, 9],
       [2, 6, 0, 3, 3]])

In [109]:
arr.shape

(5, 5)

In [110]:
np.sum(arr)

112

In [111]:
print(np.sum(arr, axis=0))

[25 25 17 20 25]


In [112]:
print(np.sum(arr, axis=1))

[25 16 19 38 14]


In [113]:
print(np.min(arr, axis=0))

[2 2 0 0 2]


In [114]:
print(np.max(arr, axis=0))

[7 6 8 9 9]


In [115]:
print(np.max(arr))
print(np.min(arr))

9
0


In [116]:
arr

array([[6, 6, 7, 4, 2],
       [7, 5, 2, 0, 2],
       [4, 2, 0, 4, 9],
       [6, 6, 8, 9, 9],
       [2, 6, 0, 3, 3]])

In [117]:
# along the row
print(np.argmin(arr, axis=0))
print(np.argmax(arr, axis=0))

[4 2 2 1 0]
[1 0 3 3 2]


In [118]:
print(np.mean(arr))

4.48


In [119]:
print(np.mean(arr, axis=0))

[5.  5.  3.4 4.  5. ]


In [120]:
print(np.mean(arr, axis=1))

[5.  3.2 3.8 7.6 2.8]


In [121]:
print(np.median(arr))

4.0


In [122]:
arr1 = np.random.rand(100)
# compute 5, 65, and 95 percentiles of the array
print(np.percentile(arr1, [5, 65, 95]))

[0.07570485 0.65035673 0.93004927]


In [123]:
print(np.std(arr))

2.7874002224294956


In [124]:
print(np.var(arr, axis=1))

[3.2  6.16 8.96 1.84 3.76]


In [125]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

In [126]:
# return an array of bools
print(arr1 == arr2)

[False False  True False False]


In [127]:
print(arr1 < 3)

[ True  True False False False]


In [128]:
arr1[arr1 < 3]

array([1, 2])

In [129]:
arr = np.array(range(100)).reshape((10,10))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [130]:
print(arr[5][5])
# or more concisely
print(arr[5,5])

55
55


In [131]:
print(arr[1:3, 4:6])

[[14 15]
 [24 25]]


In [133]:
# ellipsis slicing: auto-complete the dimensions
arr = np.array(range(16)).reshape(2,2,2,2)
# equivalent to arr[0,:,:,:]
print(arr[0, ...])

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [134]:
arr[1:3,:] = 100    # or simply arr[1:3]
arr[:,8:] = 100
print(arr)

[[[[  0   1]
   [  2   3]]

  [[  4   5]
   [  6   7]]]


 [[[100 100]
   [100 100]]

  [[100 100]
   [100 100]]]]


In [135]:
arr1 = np.arange(25).reshape((5,5))
bools = np.array([True, True, False, True, False])
print(arr1[bools])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [136]:
~bools

array([False, False,  True, False,  True])

In [137]:
print(arr1[~bools])


[[10 11 12 13 14]
 [20 21 22 23 24]]


In [138]:
arr2 = np.array([1,2,3,4,5])
(arr2<2) | (arr2>4)

array([ True, False, False, False,  True])

In [139]:
# multiple conditions
print(arr1[(arr2<2) | (arr2>4)])

[[ 0  1  2  3  4]
 [20 21 22 23 24]]


In [141]:
arr = np.random.rand(10,10)
arr

array([[0.72609133, 0.97585208, 0.51630035, 0.32295647, 0.79518619,
        0.27083225, 0.43897142, 0.07845638, 0.02535074, 0.96264841],
       [0.83598012, 0.69597421, 0.40895294, 0.17329432, 0.15643704,
        0.2502429 , 0.54922666, 0.71459592, 0.66019738, 0.2799339 ],
       [0.95486528, 0.73789692, 0.55435405, 0.61172075, 0.41960006,
        0.24773099, 0.35597268, 0.75784611, 0.01439349, 0.11607264],
       [0.04600264, 0.0407288 , 0.85546058, 0.70365786, 0.47417383,
        0.09783416, 0.49161588, 0.47347177, 0.17320187, 0.43385165],
       [0.39850473, 0.6158501 , 0.63509365, 0.04530401, 0.37461261,
        0.62585992, 0.50313626, 0.85648984, 0.65869363, 0.16293443],
       [0.07056875, 0.64241928, 0.02651131, 0.58577558, 0.94023024,
        0.57547418, 0.38816993, 0.64328822, 0.45825289, 0.54561679],
       [0.94146481, 0.38610264, 0.96119056, 0.90535064, 0.19579113,
        0.0693613 , 0.100778  , 0.01822183, 0.09444296, 0.68300677],
       [0.07118865, 0.31897563, 0.8448753

In [142]:
# select arr[3,3], arr[1,2], arr[2,1]
print(arr[[3,1,2], [3,2,1]])

[0.70365786 0.40895294 0.73789692]


In [143]:
# select rows 3,1,2 and columns 6,4,8 
print(arr[[3,1,2]][:, [6,4,8]])

[[0.49161588 0.47417383 0.17320187]
 [0.54922666 0.15643704 0.66019738]
 [0.35597268 0.41960006 0.01439349]]


In [144]:
# dimension inference using any negative number (usually -1)
arr = np.array(range(16)).reshape((4,-1))
print(arr.shape)

(4, 4)


In [145]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [148]:
np.where(arr>5)

(array([1, 1, 2, 2, 2, 2, 3, 3, 3, 3]), array([2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))

In [150]:
print(arr[arr>5])    # or arr[np.where(arr>5)]

[ 6  7  8  9 10 11 12 13 14 15]


In [149]:
arr[np.where(arr>5)]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [151]:
print(np.where(arr>5, -1, 10))

[[10 10 10 10]
 [10 10 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [152]:
print(np.argwhere(arr>5))

[[1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]


In [153]:
arr = np.random.rand(3,4)

In [154]:
# the following methods return a copy
print(arr.T)
# or 
print(np.transpose(arr))
# or
print(arr.transpose())

[[0.3200496  0.90538198 0.95060715]
 [0.89552323 0.09128668 0.57343789]
 [0.38920168 0.31931364 0.63183721]
 [0.01083765 0.95006197 0.44844552]]
[[0.3200496  0.90538198 0.95060715]
 [0.89552323 0.09128668 0.57343789]
 [0.38920168 0.31931364 0.63183721]
 [0.01083765 0.95006197 0.44844552]]
[[0.3200496  0.90538198 0.95060715]
 [0.89552323 0.09128668 0.57343789]
 [0.38920168 0.31931364 0.63183721]
 [0.01083765 0.95006197 0.44844552]]


In [155]:
arr.flatten()

array([0.3200496 , 0.89552323, 0.38920168, 0.01083765, 0.90538198,
       0.09128668, 0.31931364, 0.95006197, 0.95060715, 0.57343789,
       0.63183721, 0.44844552])

In [156]:
arr = np.array([1,2,3])

In [157]:
# append a scalar and return a copy
arr1 = np.append(arr, 4)    
print(arr1)

[1 2 3 4]


In [158]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])    
print(arr2)

[1 2 3 4 5 6]


In [159]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)    
print(arr3)

[100   1   2   3]


In [160]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [1,2,3])    
print(arr3)

[1 2 3 1 2 3]


In [161]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [162]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]


In [163]:
arr = np.array([1,2,3])

In [164]:
# the following methods are all deep copy
arr1 = np.copy(arr)
# or 
arr1 = arr.copy()
# or 
arr1 = np.array(arr, copy=True)

In [165]:
arr1

array([1, 2, 3])

In [166]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [167]:
arr1

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [168]:
arr2

array([[5, 6, 7, 8],
       [5, 6, 7, 8]])

In [169]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [170]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [171]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [172]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [173]:
arr = np.array([1,1,2,2,3,3,4,5,6])
print(np.unique(arr))

[1 2 3 4 5 6]


In [174]:
# return the number of times each unique item appears
arr = np.array([1,1,2,2,3,3,4,5,6])
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 1 1 1]


In [175]:
arr1 = np.random.rand(5,5)
arr2 = np.random.rand(5,5)

In [176]:
# Matrix multiplication
print(arr1.dot(arr2))
# or
print(np.dot(arr1, arr2))
# or
print(arr1 @ arr2)

[[1.51133757 1.58580788 1.34602315 1.19157887 1.24962705]
 [1.50249754 1.01093641 1.09892168 1.23997597 1.27517593]
 [1.60102198 1.14443773 0.90571852 0.62351293 1.34834707]
 [1.87339883 1.35603364 1.02017037 1.3662684  1.52425915]
 [1.33251554 1.04742572 1.03037938 0.29759421 1.0969071 ]]
[[1.51133757 1.58580788 1.34602315 1.19157887 1.24962705]
 [1.50249754 1.01093641 1.09892168 1.23997597 1.27517593]
 [1.60102198 1.14443773 0.90571852 0.62351293 1.34834707]
 [1.87339883 1.35603364 1.02017037 1.3662684  1.52425915]
 [1.33251554 1.04742572 1.03037938 0.29759421 1.0969071 ]]
[[1.51133757 1.58580788 1.34602315 1.19157887 1.24962705]
 [1.50249754 1.01093641 1.09892168 1.23997597 1.27517593]
 [1.60102198 1.14443773 0.90571852 0.62351293 1.34834707]
 [1.87339883 1.35603364 1.02017037 1.3662684  1.52425915]
 [1.33251554 1.04742572 1.03037938 0.29759421 1.0969071 ]]


In [177]:
# Elementwise multiplication
arr1 * arr2

array([[0.28929335, 0.12300954, 0.24926368, 0.61152969, 0.74982212],
       [0.77856433, 0.06871269, 0.18603038, 0.0048062 , 0.42706468],
       [0.24655251, 0.37658365, 0.31805336, 0.01301756, 0.07044129],
       [0.00864592, 0.28973447, 0.00569354, 0.0099934 , 0.08238227],
       [0.04723849, 0.61314449, 0.41199966, 0.07827156, 0.03180316]])

In [178]:
print(np.linalg.det(arr1))

0.11949446130763802


In [179]:
print(np.linalg.inv(arr1))

[[-0.14169505  1.25302652  2.25439151 -1.07541046 -1.70845159]
 [-0.11618623 -0.86995933  0.3846742   0.68260522  0.43079854]
 [-0.0171608   0.99773047 -0.62713917 -0.77481936  1.15635553]
 [ 1.34827568 -0.25607624  2.69231315 -1.60319985 -2.21281619]
 [ 0.09710399 -0.70719785 -3.02093119  2.29700478  1.57475657]]


In [180]:
y = [1,2,3,4,5]
print(np.linalg.solve(arr1, y))

[-3.71636729  4.18233133  2.77938285 -8.56381765  6.68171669]
